[package]
name = "altaika-engine-datafusion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
altaika-engine = { workspace = true }
altaika-foundation = { workspace = true }
altaika-sql = { workspace = true }
arrow = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
